POST http://localhost:3001/api/notes/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFzZCIsImlkIjoiNjZlMzQ3M2ZkOThjYmM2NjZmMmIxNGI5IiwiaWF0IjoxNzI2MTcxNjgwLCJleHAiOjE3MjYxNzUyODB9.6x_N-xsLrLdRzJMVslfwCv9TXJfznxqLG90mYcChEl4

{
    "content": "Libro de nico",
    "important": true,
    "name": "nicooo"
}

###
