POST http://localhost:3001/api/notes/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imp1YW4iLCJpZCI6IjY2ZTFmNjE3ZjAyNjJkMjAyZDI3ZDU4NyIsImlhdCI6MTcyNjA4Njk5MX0.BbeVvnVjV7L28v6XJZB-XQAyDs3EEsVFk5xMjXWg0jM

{
    "content": "Libro de juan",
    "important": true
}

###
